services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livechat-backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run start:dev
    environment:
      - TZ=Asia/Seoul
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: livechat
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
