services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livechat-backend
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "npx prisma db push && npx prisma generate && npm run build && npm run start:prod"
    environment:
      - TZ=Asia/Seoul
      - CHOKIDAR_USEPOLLING=true
        - CHOKIDAR_INTERVAL=1000
    networks:
      - app-network
    mem_limit: 512m
    cpus: 0.4

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx-rtmp
    container_name: nginx-hls
    ports:
      - '2935:1935'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/liveschats.store/:/etc/nginx/cert
    restart: always
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul
    mem_limit: 128m
    cpus: 0.1

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
