services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livechat-backend
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "npx prisma db push && npx prisma generate && npm run build && npm run start:prod"
    environment:
      - TZ=Asia/Seoul
      - CHOKIDAR_USEPOLLING=true
        - CHOKIDAR_INTERVAL=1000
    networks:
      - app-network

    prisma-studio:
      image: prismagraphql/prisma
      container_name: prisma-studio
      ports:
        - '5555:5555'
      networks:
        - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx-rtmp
    container_name: nginx-hls
    ports:
      - '1935:1935'
      - '443:443'
      - '5555:5555'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/liveschats.store/:/etc/nginx/cert
      - /etc/letsencrypt/archive/liveschats.store/:/etc/archive/liveschats.store
    restart: always
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
